### ISSUE TITLE
[Bug] Joint target creation error (invalid cast String > double[])

### ISSUE THREAD

**Issue by ianisl** [visose/Robots#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What Robots version are you using?

1.1.9

### What Rhino version are you using?

Rhino 7 on Windows

### Current Behavior

Hi,

Thanks for the great library.

I am experiencing an issue with the Create Target component in Joint target mode, when supplying the angles via the Joint input. The component yields an `invalid cast String > double[]` error. See attached screenshot and minimum example file.

Important: the error only arises when using a PC with a french version of Windows (which we have to use in our school's lab). On my machine using an EN-US Windows install, everything works fine. Could it be a problem with localization of number formats in Windows (comma is used as a decimal separator in french) ? 

I have tried changing Windows number formatting settings but so far this has not helped with solving the issue.

![Capture d’écran 2022-03-10 112022](https://user-images.githubusercontent.com/5112281/157643668-15662fd5-2e7b-4308-93e8-63576f6a2b07.png)

[joint-error-example.zip](https://github.com/visose/Robots/files/8222551/joint-error-example.zip)

Thanks!

**Comment by visose** [comment]
This a broken backwards compatibility issue. In the latest release the Joints input data type has been replaced from text to a parameter to a custom "Joints" parameter. 

To fix this issue remove the joint input from the target component and add it again, then connect back the the text panel with comma separated values (this will work as before).

I will try to add some check on files saved with an older versions and update this input to the new data type automatically.

**Comment by ianisl** [comment]
Thanks for the quick reply. It works with the suggested solution 👍

**Comment by visose** [comment]
Reopening the issue until backwards compatibility is fixed, as this might happen often.

**Comment by visose** [comment]
The latest version should hopefully be able to open older files without getting this error. If you still get an you can reopen the issue.
