### ISSUE TITLE
[Bug] Conflict between Rhino3dm and RhinoCommon references

### ISSUE THREAD

**Issue by lin-ycv** [visose/Robots#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What Robots version are you using?

1.5.2

### What Rhino version are you using?

Rhino 7 on Windows

### Current Behavior

I'm developing additional custom tool for robots, but the robots nuget package relies on Rhino3dm, which conflicts with RhinoCommon
![image](https://user-images.githubusercontent.com/60565737/185316154-1b3cfbd8-9042-483d-9a4b-1ac2276c4540.png)
and I can't remove RhinoCommon reference since Grasshopper package relies on Rhinocommon.

my current solution is to assign Rhino3dm an alias, but i'm wondering if there's something that can be changed on the nuget package to make it more plug and play?

The main one i'm currently having issue with is the plane for tools, it uses Rhino3dm.Geometry.Plane.

**Comment by visose** [comment]
You might be using the wrong package:
- If you are developing a plugin for Rhino or Grasshopper, use [Robots.Rhino](https://www.nuget.org/packages/Robots.Rhino). This uses RhinoCommon and targets net48.
- If you are developing a standalone or non-Rhino application, use [Robots](https://www.nuget.org/packages/Robots). This uses Rhino3dm and targets netstandard2. There are samples of this package with Unity, Dynamo, WPF.

**Comment by lin-ycv** [comment]
Ah, my mistake, did not scroll down on the nuget list, thanks. this makes things a lot easier.
