### ISSUE TITLE
DKP-400 base moves to rhino origin in simulation

### ISSUE THREAD

**Issue by evo85210** [visose/Robots#22]
Hi Vicente,

I've download the newest version (8th/0.1.0) from the wiki download page
and I've noticed that the base for the DKP400 maves to rhino origin during simulation.
I'm using the bartlett xml+3dm (with modifications to match my setup)
screenshot of problem:
![image](https://user-images.githubusercontent.com/8411844/64103918-ca5e8200-cda5-11e9-994e-53a6058cce64.png)

Have I mis-configured something? or is this a bug?

----sidenote----
I've noticed the load tool component, how do I use it? I'm assuming I have to create a new layer with my tool mesh model and add something to the xml?

**Comment by visose** [comment]
That's not supposed to happen. I'll have a look a bit later today. Could you attach or send me your 3dm/xml combo files for your robot.

**Comment by visose** [comment]
I found the issue. Could you download and replace the 8th version and test if it works for you?

**Comment by visose** [comment]
If you find it's still not working as expecting you can reopen the issue.

**Comment by evo85210** [comment]
Confim fixed, thanks!
