### ISSUE TITLE
Linear Rail: Data conversion failed from Integer to Joints

### ISSUE THREAD

**Issue by lin-ycv** [visose/Robots#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What Robots version are you using?

1.6.7

### What Rhino version are you using?

Rhino 8 for Windows

### Current Behavior

number calculated from multiplication isn't accepted, but converting to a string using a panel is ok
![image](https://github.com/visose/Robots/assets/60565737/c06f7eb3-e1fc-4c3a-9344-493360a979ec)

### Expected Behavior

it should be able to take numbers for linear rail

**Comment by visose** [comment]
Hi, an implicit cast not being implemented is not really a bug, it would be a feature, but I can add it.
You can already cast the integer to a number (double) instead of a string.

**Comment by lin-ycv** [comment]
Thanks, I thought it's a bug because it when you input a number directly from the slider it gets converted, so I thought that logic has been implemented.

**Comment by visose** [comment]
That is due to the slider is outputting an number parameter rather than an integer.

**Comment by visose** [comment]
Integer to Joint parameter implicit cast should work now. Feel free to reopen if not working as expected.
