### ISSUE TITLE
UnitTol value to high ?

### ISSUE THREAD

**Issue by lionpeloux** [visose/Robots#37]
Hi,

I am no more using your plugin (excellent by the way :)).

However, I am using [one of your method](https://github.com/visose/Robots/blob/12988d433cd4587bc600de9a8c5699699b154233/Robots/RobotCellKuka.cs#L54) to convert GH planes to XYZABC coordinates : 

I've just fall into an extreme case where the level of UnitTol needs to be at least `1e-7` though it defaults to `1e-6` in your plugin. This causes my calibration to deviates 0.04° from what it should be. The B component was truncated to -90.00° though the true value has to be -89.96°.

Just want to let you know that maybe you should reconsider the value of UnitTol ...

**Comment by visose** [comment]
Thanks, it's amazing this plugin hasn't killed anyone yet.
