### ISSUE TITLE
ABB IRB 6700 150/3.2

### ISSUE THREAD

**Issue by Anenus** [visose/Robots#42]
Hello, will ABB IRB 6700 150 / 3.2 be available with this plugin?

**Comment by v-xup6** [comment]
You can simply add your own robot by adding the model to the 3dm file and add its parameters to the xml file.

**Comment by Anenus** [comment]
Done, thank you very much !

I'm trying to make a simple pick and place script with your plugin (only one box), but I'm struggling with the toolpath.
I created the Tool, the robot, the box and the planes (origin and target for the TCP). However, your example is very complex and doesn't really work (I wasn't able to find the commands to add/delete)

Are there any simpler examples? (for only one box to pick and place)

Thank you very much.

Regards,
Walid
________________________________
De : Victor Lin <notifications@github.com>
Envoyé : jeudi 5 novembre 2020 20:59
À : visose/Robots <Robots@noreply.github.com>
Cc : Anenus <ananewalid@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [visose/Robots] ABB IRB 6700 150/3.2 (#42)


You can simply add your own robot by adding the model to the 3dm file and add its parameters to the xml file.
